-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "companyName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL DEFAULT '',
    "companyWebsite" TEXT NOT NULL DEFAULT '',
    "vertical" TEXT NOT NULL DEFAULT '',
    "employees" TEXT NOT NULL DEFAULT '',
    "password" TEXT NOT NULL,
    "structure" TEXT NOT NULL DEFAULT '',
    "legalName" TEXT NOT NULL DEFAULT '',
    "hasDBA" TEXT NOT NULL DEFAULT 'no',
    "ein" TEXT NOT NULL DEFAULT '',
    "incorporationDate" TEXT NOT NULL DEFAULT '',
    "incorporationState" TEXT NOT NULL DEFAULT '',
    "hasOtherOwners" TEXT NOT NULL DEFAULT 'no',
    "revenue" TEXT NOT NULL DEFAULT '',
    "isOwner" TEXT NOT NULL DEFAULT 'yes',
    "dob" TEXT NOT NULL DEFAULT '',
    "hasSSN" TEXT NOT NULL DEFAULT 'yes',
    "streetAddress" TEXT NOT NULL DEFAULT '',
    "aptSuite" TEXT NOT NULL DEFAULT '',
    "city" TEXT NOT NULL DEFAULT '',
    "state" TEXT NOT NULL DEFAULT '',
    "zipCode" TEXT NOT NULL DEFAULT '',
    "country" TEXT NOT NULL DEFAULT 'US',
    "officerName" TEXT NOT NULL DEFAULT '',
    "officerTitle" TEXT NOT NULL DEFAULT '',
    "businessStreetAddress" TEXT NOT NULL DEFAULT '',
    "businessAptSuite" TEXT NOT NULL DEFAULT '',
    "businessCity" TEXT NOT NULL DEFAULT '',
    "businessState" TEXT NOT NULL DEFAULT '',
    "businessZipCode" TEXT NOT NULL DEFAULT '',
    "businessCountry" TEXT NOT NULL DEFAULT 'US',
    "socialPlatform" TEXT NOT NULL DEFAULT '',
    "onboardingCompleted" BOOLEAN NOT NULL DEFAULT false
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
